language: php
php:
  - 7.2
  - 7.3
  - 8.0

matrix:
  fast_finish: true
jobs:
  include:
    - stage: codecoverage
      if: type IN (pull_request) OR branch in (master)
      php: 7.2
      script: ./vendor/bin/codecept run unit -f --steps -v -d --coverage-xml; bash <(curl -s https://codecov.io/bash) -f tests/_output/coverage.xml;
sudo: false
dist: trusty

install:
  - composer self-update && composer --version
  - composer install

script:
  # Run the unit tests
  - ./vendor/bin/codecept run -f unit

branches:
  only:
    - master
