name: publish.yml

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Semver tags
      uses: SOLIDSoftworks/semver-tags@v1.5.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        tag-prefix: 'v'

